version: "3.8"

services:
  db:
    image: postgres:13
    container_name: furever_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: loudfisH1
      POSTGRES_DB: furever-development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
